version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      #RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    #  - ./definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - the-chamber-of-secrets
networks:
  the-chamber-of-secrets:
    driver: bridge
