name: Publish Docker image

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  DEPLOYMENT_NAME: madeye-auth-system
  IMAGE_NAME: madeye-auth
  DOCKERFILE_LOCATION: .
jobs:
  generate-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.bump-version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          MAJOR_STRING_TOKEN: 'release('
          MINOR_STRING_TOKEN: 'feat('
          PATCH_STRING_TOKEN: 'fix('
          DEFAULT_BUMP: minor
  setup-build-publish-deploy:
    needs: generate-version
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN  }}
      - name: Build ${{ env.IMAGE_NAME }} and publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ env.DOCKERFILE_LOCATION }}/Dockerfile
          push: true
          tags: tbernal121/${{ env.IMAGE_NAME }}:latest, tbernal121/${{ env.IMAGE_NAME }}:${{ needs.generate-version.outputs.new_tag }}
